# Generated by Django 4.2.22 on 2025-06-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('typical_light_requirements', models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('high', 'High Light')], default='medium', max_length=10)),
                ('typical_watering_frequency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('typical_caring_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Plant Categories',
            },
        ),
        migrations.CreateModel(
            name='ShopPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('botanical_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_plant_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('air_purifying', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.plantcategory')),
            ],
        ),
    ]
